title: Ajantha Bandara
description: Ajantha Bandara, Software Engineer, Learn Javascript, PWA, Angular, Ionic and React
author: Ajantha Bandara
logo: /static/img/avatar.JPG
github: https://github.com/ajanthab
about: Senior Software Engineer, Freelance developer

baseurl: ""
url: ""

allowsearch: true

disqus_shortname: blog-2z2syr0o6z
google_analytics: UA-144295916-1

share:
  twitter_username: \#
  fb_appid: 438793143634410


enableTags: true
tagarray: [node.js]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
